# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c3180086e9aeab301e575ff8357add7e232a1175ce835fe018dc5b56c880a0d49ae1bd1e991a370a84658d95c4e0a78ba5d2b39280e7da2ad868e00426e1228

test:
  secret_key_base: b7eb8a758bbda647b69ad3d88d38ca1c458122d1747a387f4078b1ead3f51f62e0f17acf6b8c778c5f88ed6c705a5983fdcf070b98b625e407f371201c9de237

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
